name: 'Trigger Another Workflow Infinitely (Built-in)'
description: 'Triggers another workflow using repository_dispatch'
inputs:
  workflow_file:
    description: 'The name of the workflow file to trigger (e.g., my_workflow.yml)'
    required: true
  count:
    description: 'The count to pass'
    required: true

runs:
  using: "composite"
  steps:
    - name: Trigger Workflow via repository_dispatch
      shell: bash
      env:
          GH_TOKEN: ${{ github.token }}
      run: |
        gh workflow run "${{ inputs.workflow_file }}" \
          --ref "${{ github.ref }}" \
          -f "count=$(( ${{ inputs.count }} + 1 ))"
