name: One control plane, one worker - control plane

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  one-cp-one-worker-cp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Get kubectl version
        run: |
          KUBECTL_VERSION=$(kubectl version --client --output=json | jq -r '.clientVersion.gitVersion' | sed 's/^v//')
          echo "KUBECTL_VERSION=$KUBECTL_VERSION" >> $GITHUB_ENV
          echo "KUBECTL_MINOR_VERSION=$(echo $KUBECTL_VERSION | cut -d. -f1,2)" >> $GITHUB_ENV
          echo "kubectl version: $KUBECTL_VERSION"

      - name: System prerequisites
        run: |
          # Disable swap
          sudo swapoff -a
          sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

          # Enable required cgroups
          sudo mkdir -p /etc/modules-load.d
          echo overlay | sudo tee /etc/modules-load.d/k8s.conf
          echo br_netfilter | sudo tee -a /etc/modules-load.d/k8s.conf
          sudo modprobe overlay
          sudo modprobe br_netfilter

      - name: Configure system settings
        run: |
          # sysctl params required by setup
          sudo tee /etc/sysctl.d/kubernetes.conf<<EOF
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          EOF
          sudo sysctl --system

      - name: Add repository
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gpg
          sudo mkdir -p -m 755 /etc/apt/keyrings
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v$KUBECTL_MINOR_VERSION/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring-$KUBECTL_MINOR_VERSION.gpg
          echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring-$KUBECTL_MINOR_VERSION.gpg] https://pkgs.k8s.io/core:/stable:/v$KUBECTL_MINOR_VERSION/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

      - name: Install and configure containerd
        run: |
          sudo apt-get update
          sudo apt-get install -y containerd
          sudo mkdir -p /etc/containerd
          containerd config default | sudo tee /etc/containerd/config.toml
          sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
          sudo systemctl restart containerd

      - name: Install kubeadm, kubelet
        run: |
          sudo apt-get update
          sudo apt-get install -y kubelet=$KUBECTL_VERSION-1.1 kubeadm=$KUBECTL_VERSION-1.1
          sudo apt-mark hold kubelet kubeadm

      - name: Initialize control plane
        run: |
          sudo systemctl enable --now kubelet
          sudo kubeadm config images pull

          # Capture the output of the kubeadm init command
          sudo kubeadm init --pod-network-cidr=10.244.0.0/16 > kubeadm-init.log 2>&1

          # Set up kubeconfig
          mkdir -p $HOME/.kube
          sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config

          # Extract and properly escape the join command
          JOIN_COMMAND=$(grep -A 1 "kubeadm join" kubeadm-init.log | tr '\n' ' ' | sed 's/\\$//')
          # Escape the join command for GitHub Actions
          ESCAPED_JOIN_COMMAND=$(echo "$JOIN_COMMAND" | sed 's/"/\\"/g')
          echo "JOIN_COMMAND<<EOF" >> $GITHUB_ENV
          echo "$ESCAPED_JOIN_COMMAND" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          # Print the init output without the join command
          sed '/kubeadm join/,+1d' kubeadm-init.log

      - name: Install CNI plugin
        run: |
          kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

      - name: Trigger worker node
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run "one-cp-one-worker-worker.yaml" \
            --ref "${{ github.ref }}" \
            --raw-field join_command="${JOIN_COMMAND}"

      - name: Keep alive and wait for worker
        run: |
          echo "Control plane is ready for worker node. Waiting for connection..."
          for i in {1..6}; do # 5 minutes
            kubectl get nodes -o wide
            kubectl get pods -A
            echo "Sleeping for 30 seconds..."
            sleep 30
          done
