name: Setup One Control Plane, One Worker Cluster

on:
  workflow_dispatch:

jobs:
  setup-control-plane:
    uses: ./.github/workflows/one-cp-one-worker-cp.yaml

  setup-worker-node:
    uses: ./.github/workflows/one-cp-one-worker-worker.yaml
    with:
      join_command: ${{ needs.setup-control-plane.outputs.join_command }}

