name: Setup node template

on:
  workflow_call:
    inputs:
      kubectl_version:
        required: true
        type: string
        description: "Kubectl version to install (e.g. 1.28.0)"

jobs:
  setup-node-template:
    runs-on: ubuntu-latest
    outputs:
      kubectl_version: ${{ env.KUBECTL_VERSION }}
      kubectl_minor_version: ${{ env.KUBECTL_MINOR_VERSION }}
    steps:
      - name: Set kubectl version
        run: |
          echo "KUBECTL_VERSION=${{ inputs.kubectl_version }}" >> $GITHUB_ENV
          echo "KUBECTL_MINOR_VERSION=$(echo ${{ inputs.kubectl_version }} | cut -d. -f1,2)" >> $GITHUB_ENV
          echo "kubectl version: ${{ inputs.kubectl_version }}"

      - name: System prerequisites
        run: |
          sudo swapoff -a
          sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
          sudo mkdir -p /etc/modules-load.d
          echo overlay | sudo tee /etc/modules-load.d/k8s.conf
          echo br_netfilter | sudo tee -a /etc/modules-load.d/k8s.conf
          sudo modprobe overlay
          sudo modprobe br_netfilter

      - name: Configure system settings
        run: |
          sudo tee /etc/sysctl.d/kubernetes.conf<<EOF
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          EOF
          sudo sysctl --system

      - name: Add repository
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gpg
          sudo mkdir -p -m 755 /etc/apt/keyrings
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v$KUBECTL_MINOR_VERSION/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring-$KUBECTL_MINOR_VERSION.gpg
          echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring-$KUBECTL_MINOR_VERSION.gpg] https://pkgs.k8s.io/core:/stable:/v$KUBECTL_MINOR_VERSION/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

      - name: Install and configure containerd
        run: |
          sudo apt-get update
          sudo apt-get install -y containerd
          sudo mkdir -p /etc/containerd
          containerd config default | sudo tee /etc/containerd/config.toml
          sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
          sudo systemctl restart containerd

      - name: Install kubeadm, kubelet
        run: |
          sudo apt-get update
          sudo apt-get install -y kubelet=$KUBECTL_VERSION-1.1 kubeadm=$KUBECTL_VERSION-1.1
          sudo apt-mark hold kubelet kubeadm
