name: Single Node Control Plane

on:
  workflow_dispatch:

jobs:
  setup-control-plane:
    runs-on: ubuntu-latest

    steps:
      - name: Check kubectl version
        run: |
          KUBECLT_VERSION=$(kubectl version --client --output=json | jq -r '.clientVersion.gitVersion' | sed 's/^v//')
          echo "KUBECLT_VERSION: v$KUBECLT_VERSION"

      - name: Add repository
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gpg
          sudo mkdir -p -m 755 /etc/apt/keyrings
          curl -fsSL https://pkgs.k8s.io/core:/stable:/$KUBECLT_VERSION/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring-$KUBECLT_VERSION.gpg
          echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring-$KUBECLT_VERSION.gpg] https://pkgs.k8s.io/core:/stable:/$KUBECLT_VERSION/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

      - name: Install kubeadm, kubelet # kubectl is already installed
        run: |
          sudo apt-get update
          sudo apt-get install -y kubelet=$KUBECLT_VERSION-1.1 kubeadm=$KUBECLT_VERSION-1.1
          sudo apt-mark hold kubelet kubeadm

      - name: Initialize control plane
        run: |
          sudo kubeadm init --pod-network-cidr=10.244.0.0/16

      - name: Keep alive
        run: |
          # Keep the job running for demonstration
          sleep 21600  # 6 hours
