name: Single Node Control Plane

on:
  workflow_dispatch:

jobs:
  setup-control-plane:
    runs-on: ubuntu-latest

    steps:
      - name: Check kubectl version
        run: |
          KUBECLT_VERSION=$(kubectl version --client --output=json | jq -r '.clientVersion.gitVersion')

      - name: Add repository
        run: |
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

      - name: Install kubeadm, kubelet # kubectl is already installed
        run: |
          sudo apt-get update
          sudo apt-get install -y kubelet kubeadm
          sudo apt-mark hold kubelet kubeadm

      - name: Initialize control plane
        run: |
          sudo kubeadm init --pod-network-cidr=10.244.0.0/16

      - name: Keep alive
        run: |
          # Keep the job running for demonstration
          sleep 21600  # 6 hours
