name: Trigger Worker Node

on:
  workflow_run:
    workflows: ["One control plane, one worker - control plane"]
    types:
      - completed

jobs:
  start-worker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download join command
        uses: actions/download-artifact@v4
        with:
          name: join-command
          run-id: ${{ github.event.workflow_run.id }}

      - name: Read join command
        id: read-command
        run: |
          JOIN_COMMAND=$(cat join-command.txt)
          echo "join_command=$JOIN_COMMAND" >> $GITHUB_OUTPUT

      - name: Trigger Worker Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: one-cp-one-worker-worker.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: |
            {
              "join_command": "${{ steps.read-command.outputs.join_command }}"
            }
